language: ruby
rvm: 
- 2.2.2

install:
- bundle install

script:
- ./deploy.sh

branches:
  only:
    - master

env:
    secure: "LIabR5rITXSvBVJ+T9pMBwGInJXJDzYQ00hTOh4ku8Ic9yn/W3+ksvZiJbraxcDRAOI6Wf7pYdP3n7B8GVQaOdLqOLkzFLbjm5Uxckg7ASBet9jMPUksnb4oAH8k95vsMCfbmD4EB34PbAyDZxqi7Yx7OdmSdxyVhUyjJ6kWsAn3uWt5q/glbROMcTZlNMMdMO+8EIJfM2UK6SZ7sKAe/iuxeKHdp+nCoFMrYqupop6pxefQuzn5wR+sRVZyB0FKhjzoD+4k1/CE4Q8IB7SLAWJ1uNwTeMCm2RbBtyrPiNuutFAKiF3iYsO1rO436qWNZV+k7HkQuo7igkD/bb5ywFr+nEUmv0R1hU0C1PpbjO90mwuIHVDSVPtlzhUmjlzRlNaDNgNBsMZnKXM2uQXKuzEsjAeAQXIIAbHmAIhws/HFSeEk22kKXhLFh1x5xJq22hDXJZW3WL/5yRKyCIp0f7NbMlSH1JSijdGScoNMZL0Pdq65V10moSlICE62qI2mojJjPt7usRDXdGggpN/0PDQqU2fGpZPVe9BDvR/oYlA1vb2ghOQc5s7Vko+4Z9JNzFYeVvtNeKH8nmEpm0kxIyuJ5bwQpnyeX7b3zjqOAJTkTdEC3rJ/LeWi8zQUrkmspxYI9d4HR2lG4xDI2p3pRfCZ38PD8NYc4Qwp2msFX8U="
